package controller

// This file centralizes all RBAC permissions needed by the controller
// and ensures they are properly generated by Kubebuilder

// ============================================================================
// MANAGEMENT CLUSTER PERMISSIONS (where controller runs)
// ============================================================================

// Custom Resources
//+kubebuilder:rbac:groups=eksclusterregistry.spire.spiffe.io,resources=eksclusterregistries,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=eksclusterregistry.spire.spiffe.io,resources=eksclusterregistries/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=eksclusterregistry.spire.spiffe.io,resources=eksclusterregistries/finalizers,verbs=update

//+kubebuilder:rbac:groups=eksclusterregistry.spire.spiffe.io,resources=workloadidentities,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=eksclusterregistry.spire.spiffe.io,resources=workloadidentities/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=eksclusterregistry.spire.spiffe.io,resources=workloadidentities/finalizers,verbs=update

// Core Resources for Local Cluster Monitoring
//+kubebuilder:rbac:groups="",resources=pods,verbs=get;list;watch
//+kubebuilder:rbac:groups="",resources=pods/status,verbs=get;list;watch
//+kubebuilder:rbac:groups="",resources=nodes,verbs=get;list;watch
//+kubebuilder:rbac:groups="",resources=nodes/status,verbs=get;list;watch
//+kubebuilder:rbac:groups="",resources=namespaces,verbs=get;list;watch
//+kubebuilder:rbac:groups="",resources=services,verbs=get;list;watch
//+kubebuilder:rbac:groups="",resources=endpoints,verbs=get;list;watch
//+kubebuilder:rbac:groups="",resources=serviceaccounts,verbs=get;list;watch
//+kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// ConfigMaps for SPIRE Bundle Management (k8sbundle notifier)
//+kubebuilder:rbac:groups="",resources=configmaps,verbs=get;list;watch;create;update;patch;delete

// ============================================================================
// WEBHOOK MANAGEMENT
// ============================================================================

//+kubebuilder:rbac:groups=admissionregistration.k8s.io,resources=mutatingwebhookconfigurations,verbs=get;list;watch;create;update;patch
//+kubebuilder:rbac:groups=admissionregistration.k8s.io,resources=validatingwebhookconfigurations,verbs=get;list;watch;create;update;patch

// ============================================================================
// LEADER ELECTION
// ============================================================================

//+kubebuilder:rbac:groups=coordination.k8s.io,resources=leases,verbs=get;list;create;update;patch;delete
