# This file is for teaching kustomize how to substitute name and namespace reference
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - path: webhooks/clientConfig/service/name
    kind: MutatingWebhookConfiguration
- kind: ServiceAccount
  version: v1
  fieldSpecs:
  - path: subjects/name
    kind: ClusterRoleBinding

namespace:
- path: webhooks/clientConfig/service/namespace
  kind: MutatingWebhookConfiguration
- path: subjects/namespace
  kind: ClusterRoleBinding
